version: "3.5"

services:
  app:
    build: .
    container_name: ecomparser_app
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_DATABASE: ecomparser
      DB_USERNAME: ecomparser
      DB_PASSWORD: secret
    ports:
      - "8000:80"
    volumes:
      - ./config/site.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  database:
    image: mysql:5.7
    container_name: ecomparser_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ecomparser
      MYSQL_USER: ecomparser
      MYSQL_PASSWORD: secret
  dbadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ecomparser_dbadmin
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "8080:80"
